export var actions =  {
    CHANGE_AMOUNT: 'CHANGE_AMOUNT',
    CHANGE_CARD_NUMBER: 'CHANGE_CARD_NUMBER',
    CHANGE_EXPIRATION_DATE: 'CHANGE_EXPIRATION_DATE',
    CHANGE_CVV: 'CHANGE_CVV',
    CHANGE_HOLDER_NAME: 'CHANGE_HOLDER_NAME',
    SEND_PAYMENT: 'SEND_PAYMENT',
    RESET_PAYMENT_INFO: 'RESET_PAYMENT_INFO'
};

export var API_URL = 'https://alpha.antonstepanok.com/api';